version: '4'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server  # 添加此行
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "3000:3000"
    networks:
      - tourist
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client  # 添加此行
    restart: always
    depends_on:
      - server
    ports:
      - "80:80"
    networks:
      - tourist
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/init:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tourist
    networks:
      - tourist
  redis:
    image: redis:7.0.15
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./data/redis/conf:/usr/local/etc/redis
      - ./data/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - tourist
networks:
  tourist:
    name: hmall
